### PR TITLE
core: GetBucketPolicy API should return all errors.

### LINKED ISSUE #664: getBucketPolicy returns policy without statements instead of error NoSuchBucketPolicy
api-get-policy.go#81

Currently Mint fails on this, but probably this has been done on purpose. I see the following solutions:

* don't use Client::getBucketPolicy in Core, but instead, use different implementation in Core
* fix this code, and return an error code when error occurs
* fix in gateway router when we have a policy without statements, return NoSuchBucketPolicy
* fix mint and check for statements is null

### PR DESCRIPTION
**Pull request by harshavardhana**
GetBucketPolicy should return exact error received
from the server and let the caller manage it.

Fixes #664

### CODE REVIEW

File: api-get-policy.go [hunk 1]
```diff
@@ -51,12 +52,18 @@ func (c Client) ListBucketPolicies(bucketName, objectPrefix string) (bucketPolic
...
 	policyInfo, err := c.getBucketPolicy(bucketName)
-	if err != nil {
+	errResponse := ToErrorResponse(err)
+	if err != nil && errResponse.Code != "NoSuchBucketPolicy" {
 		return map[string]policy.BucketPolicy{}, err
 	}
 	return policy.GetPolicies(policyInfo.Statements, bucketName), nil
 }
 
+// Default empty bucket access policy.
```
Comment (krisis) [inline api-get-policy.go]: This can be defined as a const.
```go
const  emptyBucketPolicy = policy.BucketAccessPolicy {
  Version: "2012-10-17",
}
```

File: api-put-bucket.go [hunk 2]
```diff
@@ -163,7 +163,8 @@ func (c Client) SetBucketPolicy(bucketName string, objectPrefix string, bucketPo
 	}
 
 	policyInfo, err := c.getBucketPolicy(bucketName)
```
Comment (krisis) [inline api-put-bucket.go]: if all callers to `getBucketPolicy` should check for "NoSuchBucketPolicy", can't we check for the corresponding `errResponse.Code` inside the function and return `sentinelBucketAccessPolicy, nil`?

Comment (harshavardhana) [inline api-put-bucket.go]: That is exactly what we don't want. All callers need not check for example Core API shouldn't check.

It is a change to reflect a core API should do lower implementation and return all errors. Special interpretation is left to the caller.

File: api-get-policy.go (hunk 1 above)
Comment (harshavardhana) [inline api-get-policy.go]: Sure

Comment (harshavardhana) [inline api-get-policy.go]: Struct literals cannot be constants, keep it as var.

**Comment by harshavardhana** [comment]
> Is it possible to add a functional test that simulates the issue being fixed here?

Functional test added as well.

File: api-get-policy.go [hunk 3]
```diff
@@ -35,7 +35,8 @@ func (c Client) GetBucketPolicy(bucketName, objectPrefix string) (bucketPolicy p
 		return policy.BucketPolicyNone, err
 	}
 	policyInfo, err := c.getBucketPolicy(bucketName)
-	if err != nil {
+	errResponse := ToErrorResponse(err)
+	if err != nil && errResponse.Code != "NoSuchBucketPolicy" {
```
Comment (vadmeste) [inline api-get-policy.go]: I am not sure how this change fixes #664 ? we are not returning any error when error is NoSuchBucketPolicy

Comment (harshavardhana) [inline api-get-policy.go]: It fixes #664 because Gateway uses GetBucketPolicy() Core API directly, which would return NoSuchBucketPolicy i.e error when no bucket policy exists. This makes it easier for Gateway to have a pass-through error back to the client.

Comment (vadmeste) [inline api-get-policy.go]: yes, but notice that with this change, GetBucketPolicy() will return err = nil when getBucketPolicy() returns NoSuchBucketPolicy.

Comment (harshavardhana) [inline api-get-policy.go]: GetBucketPolicy is overridden Core API @vadmeste, what you are talking about is GetBucketPolicy(bucket, prefix) which is not changed and should be working as expected.

Comment (harshavardhana) [inline api-get-policy.go]: Look at the functional test in core_test.go to get the better idea. @vadmeste

Comment (vadmeste) [inline api-get-policy.go]: ok, understood.

Comment (vadmeste) [inline api-get-policy.go]: I think it is better if we return policy.BucketPolicyNone when we have NoSuchBucketPolicy without going to policy.GetPolicy() later.

File: api-get-policy.go [hunk 4]
```diff
@@ -51,12 +52,18 @@ func (c Client) ListBucketPolicies(bucketName, objectPrefix string) (bucketPolic
 		return map[string]policy.BucketPolicy{}, err
 	}
 	policyInfo, err := c.getBucketPolicy(bucketName)
-	if err != nil {
+	errResponse := ToErrorResponse(err)
+	if err != nil && errResponse.Code != "NoSuchBucketPolicy" {
```
Comment (vadmeste) [inline api-get-policy.go]: I think it is better if we return map[string]policy.BucketPolicy{} when we have NoSuchBucketPolicy without going to policy.GetPolicies() later.

Comment (harshavardhana) [inline api-get-policy.go]: Sure

File: api-get-policy.go (hunk 3 above)
Comment (harshavardhana) [inline api-get-policy.go]: Sure
