### PR TITLE
Handle "Not implemented" error codes in functional test

### LINKED ISSUE #834: Handle "Not implemented" error codes in functional test
In s3 gateway mode, some calls return "not implemented". 
We should handle the situation gracefully, and not fail basically. 
```
status: "NA"
alert: "Not Implemented"
```

Here is an example error. 
Please look at the error part of the entry

```

{"alert":"","args":{"destination":{},"sources":[{"Headers":{"X-Amz-Copy-Source":["minio-go-testpqymyww039cgzqvvy/srcObject"],"X-Amz-Copy-Source-If-Match":["2b5c91ad399409ec9b409b66f5bb00fb"],"X-Amz-Copy-Source-Range":["bytes=0-5242879"]}},{"Headers":{"X-Amz-Copy-Source":["minio-go-testpqymyww039cgzqvvy/srcObject"],"X-Amz-Copy-Source-If-Match":["2b5c91ad399409ec9b409b66f5bb00fb"]}},{"Headers":{"X-Amz-Copy-Source":["minio-go-testpqymyww039cgzqvvy/srcObject"],"X-Amz-Copy-Source-If-Match":["2b5c91ad399409ec9b409b66f5bb00fb"]}},{"Headers":{"X-Amz-Copy-Source":["minio-go-testpqymyww039cgzqvvy/srcObject"],"X-Amz-Copy-Source-If-Match":["2b5c91ad399409ec9b409b66f5bb00fb"]}},{"Headers":{"X-Amz-Copy-Source":["minio-go-testpqymyww039cgzqvvy/srcObject"],"X-Amz-Copy-Source-If-Match":["2b5c91ad399409ec9b409b66f5bb00fb"]}},{"Headers":{"X-Amz-Copy-Source":["minio-go-testpqymyww039cgzqvvy/srcObject"],"X-Amz-Copy-Source-If-Match":["2b5c91ad399409ec9b409b66f5bb00fb"]}},{"Headers":{"X-Amz-Copy-Source":["minio-go-testpqymyww039cgzqvvy/srcObject"],"X-Amz-Copy-Source-If-Match":["2b5c91ad399409ec9b409b66f5bb00fb"]}},{"Headers":{"X-Amz-Copy-Source":["minio-go-testpqymyww039cgzqvvy/srcObject"],"X-Amz-Copy-Source-If-Match":["2b5c91ad399409ec9b409b66f5bb00fb"]}},{"Headers":{"X-Amz-Copy-Source":["minio-go-testpqymyww039cgzqvvy/srcObject"],"X-Amz-Copy-Source-If-Match":["2b5c91ad399409ec9b409b66f5bb00fb"]}},{"Headers":{"X-Amz-Copy-Source":["minio-go-testpqymyww039cgzqvvy/srcObject"],"X-Amz-Copy-Source-If-Match":["2b5c91ad399409ec9b409b66f5bb00fb"]}}]},"duration":5218,"error":"Error in upload-part-copy - A header you provided implies functionality that is not implemented","function":"ComposeObject(destination, sources)","message":"ComposeObject failed","name":"minio-go","status":"fail"}

```

### PR DESCRIPTION
**Pull request by kannappanr**
Check for the error message "Not Implemented" in ComposeObject
API call. If it is seen, log NA for the test and log the error, but continue
with the test.

Fixes #834

### CODE REVIEW

**Comment by ebozduman** [comment]
LGTM

File: functional_tests.go [hunk 1]
```diff
@@ -62,6 +62,7 @@ const (
 	secretKey      = "SECRET_KEY"
 	enableHTTPS    = "ENABLE_HTTPS"
 )
+const notImplemented = "A header you provided implies functionality that is not implemented"
```
Comment (harshavardhana) [inline functional_tests.go]: We don't need to look the string we can simply look for the error code.

File: functional_tests.go [hunk 2]
```diff
@@ -4478,6 +4479,10 @@ func testComposeMultipleSources(c *minio.Client) {
 	}
 	err = c.ComposeObject(dst, srcs)
 	if err != nil {
+		if strings.Contains(err.Error(), notImplemented) {
```
Comment (harshavardhana) [inline functional_tests.go]: Convert this into a function lets like 

```
isErrNotImplemented()
```

```go
func isErrNotImplemented(err error)  bool {
   errResp := ToErrorResponse(err)
   return errResp.Code != "NotImplemented"
}
```

File: functional_tests.go [hunk 3]
```diff
@@ -158,6 +158,11 @@ func cleanupBucket(bucketName string, c *minio.Client) error {
 	return err
 }
 
+func isErrNotImplemented(err error) bool {
+	errResp := minio.ToErrorResponse(err)
```
Comment (harshavardhana) [inline functional_tests.go]: This can be written in even one liner.. 

```
func isErrNotImplemented(err error) bool {
         return minio.ToErrorResponse(err).Code != "NotImplemented"
}
```

Comment (kannappanr) [reply functional_tests.go]: done.
