### PR TITLE
avoid unnecessary stat call during single copy

### LINKED ISSUE #961: [SSE]: CopyObject fails for encrypted-to-unencrypted object
## What I did

```
package main

import (
	"crypto/tls"
	"log"
	"net/http"

	"github.com/minio/minio-go"
	"github.com/minio/minio-go/pkg/encrypt"
)

func main() {
	accessKey, secretKey := "", ""
	minioClient, err := minio.New("s3.amazonaws.com", accessKey, secretKey, true)
	if err != nil {
		log.Fatalln(err)
	}

	minioClient.SetCustomTransport(&http.Transport{
		TLSClientConfig: &tls.Config{
		  InsecureSkipVerify: true,
		},
	})

	bucket, object, file := "bucket", "object", "your-file"
	options := minio.PutObjectOptions{
		ServerSideEncryption: encrypt.DefaultPBKDF([]byte("123456"), []byte(bucket+object)),
	}
	if _, err = minioClient.FPutObject(bucket, object, file, options); err != nil {
		log.Fatalln(err)
	}

	src := minio.NewSourceInfo(bucket, object, encrypt.SSECopy(encrypt.DefaultPBKDF([]byte("123456"), []byte(bucket+object))))
	dst, _ := minio.NewDestinationInfo(bucket, object+"-copy", nil, nil)
	if err = minioClient.CopyObject(dst, src); err != nil {
		log.Fatalln(err)
	}
	log.Println("OK")
}
```

### What did you expect to see

Expected `OK`

### What did you see instead

Could not stat object - bucket/object: 400 Bad Request

### Solution

The problem is that `ComposeObject` (which is called by `CopyObject`) tries a Stat per source-info to do some checks and get the size of all source objects. The Stat fails because only the SSE-C copy headers are provided. The solution is to make `CopyObject` a separate call.
To be precise this issue affects also `ComposeObject` for multiple source objects. However I don't see how this can be fixed without changing other composing behavior.

### PR DESCRIPTION
**Pull request by aead**
This change separates the copy logic from the compose logic.
This allows users to specify SSE-C copy encryption directly.
Additionally it saves a HEAD request. 

Fixes #961

### CODE REVIEW

File: pkg/encrypt/server-side.go [hunk 1]
```diff
@@ -101,6 +101,21 @@ func NewSSEC(key []byte) (ServerSide, error) {
 	return sse, nil
 }
 
+// SSE transforms a SSE-C copy encryption into a SSE-C encryption.
+// It is the inverse of SSECopy(...).
+//
+// If the provided sse is no SSE-C copy encryption SSE returns
+// sse unmodified.
+func SSE(sse ServerSide) ServerSide {
```
Comment (harshavardhana) [inline pkg/encrypt/server-side.go]: SSE() should be called as SSEC() here i think, since it might be confusing when we implement NewSSE()

Comment (aead) [reply pkg/encrypt/server-side.go]: `NewSSE()` is already [there](https://github.com/minio/minio-go/blob/master/pkg/encrypt/server-side.go#L97) - as well as the `NewSSEC()` [function](https://github.com/minio/minio-go/blob/master/pkg/encrypt/server-side.go#L113)

Semantically the current solution is sound:
`encrypt.SSE(encrypt.NewSSE())` is equivalent to `encrypt.NewSSE()`
`encrypt.SSE(encrypt.DefaultPBKDF(...))` is equivalent to `encrypt.DefaultPBKDF(...)`
`encrypt.SSE(encrypt.SSECopy(encrypt.NewSSE()))` is equivalent to `encrypt.NewSSE()`
`encrypt.SSE(nil)` is equivalent to `nil`
a.s.o.

`SSE()` and `SSECopy()` are "generic" functions. Specifying `copy` only for SSE-C may be correct with respect to functionality (only SSE-C distinguish copy / non-copy headers) but probably leads  to more complexity for the client because he/she has to understand all that.
Right now `encrypt.SSE(encrypt.SSE(encrypt.SSECopy(encrypt.NewSSE())))` boils down to `encrypt.SSE()` semantically. So I don't see how clients can get confused - except if they want to do advanced things **and** don't read the function doc.

Comment (aead) [reply pkg/encrypt/server-side.go]: So you're saying a user could confuse the function call `encrypt.SSE(..)` with a type conversion:
`encrypt.SSE(...)` like `[]byte(...)`? (A struct initialization would require `{` brackets)
 
Semantically it's exactly that - but as a function. Another (maybe more explicit) version would
be `encrypt.ToSSE(...)` - however the API would look a bit odd with `SSECopy()` and `ToSSE()`.
Or we break compatibility and add to functions to the interface to convert back and forth.
(There should be no other implementations because there is only SSE-S3, SSE-C and SSE-KMS)

Comment (harshavardhana) [reply pkg/encrypt/server-side.go]: okay fair enough I think its fine...

File: functional_tests.go [hunk 2]
```diff
@@ -5644,6 +5644,60 @@ func testEncryptedCopyObjectV2() {
 	testEncryptedCopyObjectWrapper(c)
 }
 
+func testDecryptedCopyObject() {
```
[the remark this answers is not in the document]
Comment (aead) [reply functional_tests.go]: Oh, was just copy-past mistake. Changed to `New` - IMO separate tests for different signature types are not needed...
