### PR TITLE
tests: Reduce context timeout to avoid false positives

### LINKED ISSUE #880: FPutObject functional test fails with "Request context cancellation failed"
Ran minio-go (release 4.0.3) functional tests using mint Docker build, with Nov 17th minio release, `minio.RELEASE.2017-11-17T01-22-21Z`, in fs mode with HTTPS with (self signed certificate), and FPutObject api command test failed.
Here is the captured  json information:
```
{
  "alert": "",
  "args": {
    "bucketName": "minio-go-testarssrtynmdgrt9h1v",
    "ctx": {
      "Context": 0
    },
    "fileName": "",
    "objectName": "minio-go-testarssrtynmdgrt9h1vFPutObjectWithContext",
    "opts": ""
  },
  "duration": 9,
  "function": "FPutObject(bucketName, objectName, fileName, opts)",
  "message": "Request context cancellation failed",
  "name": "minio-go",
  "status": "fail"
}
```

### PR DESCRIPTION
**Pull request by harshavardhana**
context timeout tests had long timeouts leading
to false positives in some cases when functional
tests are run against faster disks.

Reduce them such that the possibility of this
would never occur in future usage.

Fixes #880

### CODE REVIEW

**Comment by kannappanr** [comment]
function test check on Travis failed for the following 

{"alert":"","args":{"bucketName":"minio-go-testxns0okpetpou4rs6k","ctx":{"Context":0},"objectName":"0n1i3humrguu2dnrzrtgg0vaf49g3z"},"duration":156,"function":"GetObjectWithContext(ctx, bucketName, objectName)","message":"GetObjectWithContext failed due to non-cancellation upon short timeout","name":"minio-go","status":"fail"}

**Comment by harshavardhana** [comment]
The PR is updated and fixed the context usage properly.

File: functional_tests.go [hunk 1]
```diff
@@ -6342,17 +6346,21 @@ func testGetObjectWithContextV2() {
...
 
-	// Read the data back
 	r, err := c.GetObjectWithContext(ctx, bucketName, objectName, minio.GetObjectOptions{})
 	if err != nil {
-		logError(function, args, startTime, "", "GetObjectWithContext failed due to non-cancellation upon short timeout", err)
+		logError(function, args, startTime, "", "GetObjectWithContext failed unexpectedly", err)
+		return
+	}
+	if _, err = r.Stat(); err == nil {
+		logError(function, args, startTime, "", "GetObjectWithContext did not failue to due to cancellation upon short timeout", err)
```
Comment (poornas) [inline functional_tests.go]: typo ->failue

**Comment by harshavardhana** [comment]
Any other concerns other than the typo ?

File: functional_tests.go [hunk 2]
```diff
@@ -1803,18 +1803,18 @@ func testPutObjectWithContext() {
...
 
-	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
+	ctx, cancel := context.WithTimeout(context.Background(), 1*time.Millisecond)
 	args["ctx"] = ctx
 	args["opts"] = minio.PutObjectOptions{ContentType: "binary/octet-stream"}
 	defer cancel()
 
 	_, err = c.PutObjectWithContext(ctx, bucketName, objectName, reader, int64(bufSize), minio.PutObjectOptions{ContentType: "binary/octet-stream"})
-	if err != nil {
+	if err == nil {
```
Comment (kannappanr) [inline functional_tests.go]: Looks like this has been changed to expect the API to fail. If that is the case, the comment needs to reflect that.

File: functional_tests.go [hunk 3]
```diff
@@ -6073,17 +6073,21 @@ func testGetObjectWithContext() {
...
-	// Read the data back
 	r, err := c.GetObjectWithContext(ctx, bucketName, objectName, minio.GetObjectOptions{})
 	if err != nil {
-		logError(function, args, startTime, "", "GetObjectWithContext failed - request timeout not honored", err)
+		logError(function, args, startTime, "", "GetObjectWithContext failed unexpectedly", err)
 		return
 	}
-	ctx, cancel = context.WithTimeout(context.Background(), 3*time.Minute)
+	if _, err = r.Stat(); err == nil {
+		logError(function, args, startTime, "", "GetObjectWithContext did not failure to due to cancellation upon short timeout", err)
```
Comment (kannappanr) [inline functional_tests.go]: typo: failure needs to be fail

File: functional_tests.go [hunk 4]
```diff
@@ -6342,17 +6346,21 @@ func testGetObjectWithContextV2() {
...
 
-	// Read the data back
 	r, err := c.GetObjectWithContext(ctx, bucketName, objectName, minio.GetObjectOptions{})
 	if err != nil {
-		logError(function, args, startTime, "", "GetObjectWithContext failed due to non-cancellation upon short timeout", err)
+		logError(function, args, startTime, "", "GetObjectWithContext failed unexpectedly", err)
+		return
+	}
+	if _, err = r.Stat(); err == nil {
+		logError(function, args, startTime, "", "GetObjectWithContext did not failure to due to cancellation upon short timeout", err)
```
Comment (kannappanr) [inline functional_tests.go]: The comment needs to be clear

**Comment by harshavardhana** [comment]
fixed comments PTAL @kannappanr @poornas
