### PR TITLE
api: Retry only request body is seekable

### LINKED ISSUE #791: Functional tests not passing when Minio server has a new default region
When I set Minio region to "us-west-2" in ~/.minio/config.json, functional tests won't pass anymore:

```
$ go run functional_tests.go
...
INFO[0015]                                               file=functional_tests.go function:=main.testGetObjectClosedTwice line#=665
FATA[0041] Error:Put http://localhost:9000/minio-go-testiuzn23cfq9jrzlcnz/1yzgz903xtgj9tceycazirws0cmlla: Connection closed by foreign host http://localhost:9000/minio-go-testiuzn23cfq9jrzlcnz/1yzgz903xtgj9tceycazirws0cmlla. Retry again.minio-go-testiuzn23cfq9jrzlcnz1yzgz903xtgj9tceycazirws0cmlla  file=functional_tests.go function:=main.testGetObjectClosedTwice line#=705
exit status 1
```

### PR DESCRIPTION
**Pull request by vadmeste**
It doesn't make sense to retry a HTTP request when its body is not
seekable. Req Body can be delivered by a developer such as in
PutObject() API.

Partially fix - ref #791

### CODE REVIEW

File: api.go [hunk 1]
```diff
@@ -519,15 +519,21 @@ func (c Client) executeMethod(method string, metadata requestMetadata) (res *htt
...
 	// blank identifiers is only supported since go1.4
 	// https://golang.org/doc/go1.4#forrange.
-	for range c.newRetryTimer(MaxRetry, DefaultRetryUnit, DefaultRetryCap, MaxJitter, doneCh) {
+	for range c.newRetryTimer(reqRetry, DefaultRetryUnit, DefaultRetryCap, MaxJitter, doneCh) {
 		// Retry executes the following function body if request has an
 		// error until maxRetries have been exhausted, retry attempts are
 		// performed after waiting for a given period of time in a
 		// binomial fashion.
-		if isRetryable {
+		if isSeekable {
```
Comment (harshavardhana) [inline api.go]: Why change the variable name? @vadmeste `isRetryable` is fine here. isSeekable is not providing any meaning.

File: api.go [hunk 2]
```diff
@@ -519,15 +519,21 @@ func (c Client) executeMethod(method string, metadata requestMetadata) (res *htt
 	// Indicate to our routine to exit cleanly upon return.
 	defer close(doneCh)
 
+	// Retry only when reader is seekable
+	reqRetry := MaxRetry
+	if !isSeekable {
+		reqRetry = 1
```
Comment (harshavardhana) [inline api.go]: We should set this value perhaps in above `metadata.contentBody` fold itself.  Avoids having multiple ifs.

File: api.go (hunk 1 above)
Comment (vadmeste) [reply api.go]: > Why change the variable name? @vadmeste isRetryable is fine here. isSeekable is not providing any meaning. Its also not associated with what this PR tries to fix.

Yeah, it is a simple change, I thought isSeekable is more precise than isRetryable, will revert
